---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: weave-gitops-repo
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://helm.gitops.weave.works
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  chart:
    spec:
      chart: weave-gitops
      sourceRef:
        kind: HelmRepository
        name: weave-gitops-repo
  interval: 1h0m0s
  releaseName: weave-gitops
  targetNamespace: demo-ns
  values:
    ingress:
      enabled: true
      className: ""
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
        - host: gitops.flux.cloudnativerioja.com
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - gitops.flux.cloudnativerioja.com
          secretName: gitops-flux-tls
