apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cluster-deploy
  namespace: flux-system
spec:
  interval: 30s
  url: https://github.com/cloudnativerioja/demos-iac
  ref:
    branch: master
---

