apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cluster-deploy
  namespace: flux-system
spec:
  interval: 30s
  url: https://github.com/cloudnativerioja/demos-iac
  ref:
    branch: master
---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: cluster-deploy-tf-controller
  namespace: terraform
spec:
  approvePlan: ""
  path: ./terraform/civo/
  storeReadablePlan: "human"
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: cluster-deploy
    namespace: flux-system
  varsFrom:
    - kind: Secret
      name: civo-token
      varsKeys:
        - civo_token
