apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cluster-user-auth
  namespace: demo-ns
spec:
  encryptedData:
    password: AgBV50fRpDeUlEghE15PbcAJ+l9F2QcR68t+IiXBS1owpQaOr6O+DHBMwLyQxkc4vkBHXOmoNRqba9Y/liE96/0/KRbublIAoV6kDr+x4iT0YejMp9qGzX9uCOBFsB5ZzJ//HsSx2/z3uB8pg0N2CrE+hQU2l1/vhPh+7GH/QG+RvzyljrIXyMXJlT7w1tSbjK0zE5SjW3PJsQMieKOBnNY3LYH7CI3ddepmqxwkVSFK/WglyO9r3DXyiwphrTolwTANqY18+5TW+BA5KdgAb2GRVI02ZBtmq8IS1cRg+cOZWkMYFAIxzf7oaDc8Gxs2Mi6xQc9w9d60s7VvpIOK4QLzmS6oKHgXTDO6BFVekuiSHTLZlwvFe9pXZ/ITXcP7bLXh7ewmi9biFLqHYFj0QCHMg4Qda2v6TtlmQ4uhH3bQT6VjB13/oFSU7Yr8ghItD4O1wHayvsDiDvaYrCx7t8pi62acfNZMjdV00wuWfVdstmdJ1DFSJj9YYfRA+nQBVPwVSH+OctPn7IjRofeVv1MaBZDtRaG2RpfiK+fTWrFzoERg8tYng+DaDUg5wdmzWm5wicYHi77ZhopyMGF7Vugdc6xMzRNjrIM0sJJEDM5n+/oBXFjEcjdi28JKAtnkZaAkAgCa89XJX66U05IOhxmaqBwPWKGHzh4Uqyki0sdbRz7vwZ/i7MOKdVM6K0QmrL7YYqX9HKSNWRAMMhCITe8b8KXxX+fWiuk5VfcZKTXQC6EoM7nh4v7GlY+deplG5Ji7ZPfpeWY=
    username: AgBhNoI+P+GlaipsCnUlaTQD4j8ohILQM6GupJ/xyxc7F8HSQgF6FXbRaxdPr6WjfMIy1Qod69s2Oeu7Ozf8Mt0/Rr24hR5BXztx8GHXF8xibqjQfmTpClkBwAwdFtE/pgcgKBlfQnA5XIrU1JXBixHvIK4eloitivWLVkspog1cUvMLlcqX3vBnbPjcZCIsZj4UGSuhE5gfd45BOLCDqrBvowtA1Km9rdu99Fj9oM+ufjIjLxGuC7+YozGkqjHBVbHDiziyyMiK1Lhn2aDZ8yHO+bNc/97ZhplRAtZMjAwUgHVvy70kYtrT61KcgC60MqD4ATz2x037Ypv3UMrEoDHa/RXT87jCmvt8zFxtREMFETVkBd0Ds/3Ftr8ODF9//mt6C7YYxUxXJFWI5L6IP5U3NsHFhrgWovMW7U63Vsk26rfVH54F7s3B0NvCUEJm2Wl8u6iml7EKvP/f88V8WvHBVViKTNRkLrZq3QBGEYQu0Jq/WnRFFgbgKB+Bm5WJ4Sxwr4/HiyGo5i6ww6XECGoRYhVr6o4zqQEI+XdIjitBz4iQwqqtI/t/Sajclu5K4SOXRSm+VE5hMNiWmb4ErkJTLIfFmqjreVeDpqY1dV6gRHZXCDkb0B4pXrAvVp7VX1tqYyRstGoK6dQfZqw1y9xT2kDQhRRdsTqt7ESThxhniNoEh/RzoPq6VhCkELUMiKXQ5f+V2Q==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cluster-user-auth
      namespace: demo-ns

