---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: manifests
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: demo-ns
  sourceRef:
    kind: GitRepository
    name: flux-manifests
  path: "./core/"
  prune: true
  timeout: 1m
